import Head from "next/head";
import { ReactElement, ReactNode, useContext } from "react";
import {
  SidebarContext,
  SidebarContextProps,
} from "../context/SidebarContextProvider";
import Sidebar from "./Sidebar/Sidebar";
import SidebarButton from "./Sidebar/SidebarButton";

type LayoutProps = {
  title: string;
  children: ReactElement | ReactNode;
};

export default function Layout({ title, children }: LayoutProps) {
  const { open, setOpen } = useContext(SidebarContext) as SidebarContextProps;

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative flex min-h-screen flex-row flex-nowrap">
        {/* <SidebarButton /> */}
        <Sidebar />
        <main className="flex-1">{children}</main>
      </div>
    </>
  );
}
