import { GetServerSidePropsContext } from "next";
import { Provider } from "next-auth/providers";
import { getProviders, signIn } from "next-auth/react";
import Head from "next/head";

type LoginProps = {
  providers: Provider;
};

export default function Login({ providers }: LoginProps) {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {Object.values(providers).map((provider) => (
          <section
            key={provider.name}
            className="flex min-h-full w-full flex-col items-center justify-center gap-10"
          >
            <h1 className="text-7xl font-bold text-white">Spotify Clone</h1>
            <button
              type="button"
              onClick={() => signIn(provider.id, { callbackUrl: "/" })}
              className="rounded-full bg-white py-2 px-10 text-2xl font-bold"
            >
              Login
            </button>
          </section>
        ))}
      </main>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const providers = await getProviders();
  return {
    props: {
      providers,
    },
  };
}
